---
- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    setup_name: iptables
    ansible_role: base/iptables
    templates:
      - alpine/setup.sh
      - main.iptables
      - alpine/dns-rules.sh
      - alpine/dns-rules.conf
    executable_files:
      - setup.sh
      - dns-rules.sh
