---
- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    setup_name: netdata
    ansible_role: service/netdata
    templates:
      - alpine/setup.sh
      - alpine/netdata.conf
    executable_files:
      - setup.sh