---
- set_fact:
    setup_name: home-assistant

- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    ansible_role: service/home-assistant
    templates:
      - alpine/setup.sh
      #- alpine/home-assistant.rc
    executable_files:
      - setup.sh
      #- home-assistant.rc

- include_role:
    name: utils/alpine
    tasks_from: podman-service
  vars:
    host_network: True
    privileged: True
    volumes:
      - /var/home-assistant/config:/config
    env_vars:
      TZ: America/Chicago
    image: ghcr.io/home-assistant/home-assistant
    tag: stable
