---
- name: >
    main
    : Verify Sway User Directory Present
  file:
    path: "{{ user.home }}/.config/sway"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  become: True

- name: >
    main
    : Template Config
  template:
    src: "{{ inventory_hostname }}.j2"
    dest: "{{ user.home }}/.config/sway"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True
