---
- name: >
    main
    : Install build packages
  apt:
    name:
      - build-essential
      - dkms
      - git
    state: present
  become: True

uses_asus_wifi_dongle

git clone https://github.com/cilynx/rtl88x2bu

From: https://askubuntu.com/questions/1079377/how-do-i-install-drivers-for-realtek-rtl8812bu

sudo apt-get install build-essential dkms git
git clone https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959
cd rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959
VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
sudo dkms add -m rtl88x2bu -v ${VER}
sudo dkms build -m rtl88x2bu -v ${VER}
sudo dkms install -m rtl88x2bu -v ${VER}
sudo modprobe 88x2bu