---
- name: >
    locale
    : Set locale
  command: localectl set-locale en_US.UTF-8
  become: True

# - name: >
#     locale
#     : Set Locale
#   lineinfile:
#     path: /etc/locale.gen
#     line: en_US.UTF-8 UTF-8
#   become: True

# - name: >
#     locale
#     : Generate encoding and update locale
#   command: "{{ item }}"
#   become: True
#   loop: 
#     - locale-gen en_US.UTF-8
#     - update-locale en_US.UTF-8
