---
- include_tasks: "debian/update.yml"

- include_tasks: "debian/auto-updates.yml"

- include_tasks: hostname.yml

- include_tasks: locale.yml

- include_tasks: time-zone.yml

- include_tasks: mounts.yml

- include_tasks: root-shell.yml

-  


- name: >
    debian/main
    : Disable pcspkr (to disable system bell)
  modprobe:
    name: pcspkr
    state: absent
    persistent: absent
  become: True
