---
- include_tasks: "{{ system }}/main.yml"


- name: >
    main
    : Add appropriate login users to docker group
  user:
    name: "{{ login_user.name }}"
    groups:
      - docker
    append: True
  loop_control:
    loop_var: login_user
  loop: "{{ login_users }}"
  when: "{{ login_user.docker | default('') }}"
  become: True
