---
- name: >
    fedora/setup
    : Install MPD
  dnf:
    name: mpd
  become: True

- name: >
    fedora/setup
    : Setup MPD Services
  include_tasks: fedora/service.yml
  loop: "{{ mpd_services }}"
  loop_control:
    loop_var: mpd
