---
- name: >-
    apply-setup
    : Remove existing setup dir
  delegate_to: localhost
  shell: ssh {{ inventory_hostname }} rm -rf setup

- name: >-
    apply-setup
    : Copy setup directory
  delegate_to: localhost
  shell: >-
    scp -Or
    {{ local_build_dir }}/
    {{ inventory_hostname }}:setup/

# - name: >-
#     apply-setup
#     : Run setup script
#   delegate_to: localhost
#   shell: >-
#     ssh {{ inventory_hostname }} screen -d -m setup/setup.sh
