---
- name: >
    main-setup
    : Get 
  delegate_to: localhost
  find:
    paths:
      - "{{ local_build_dir }}"
    file_type: directory
  register: setup_stage_dirs

# - debug:
#     msg: "{{ setup_stage_dirs }}"


- set_fact:
    setup_stages: >-
      {%
        for f in setup_stage_dirs.files
          %}{{ f.path | basename
          }}{% if not loop.last %} {% endif
          %}{%
        endfor
      %}


- name: >
    main-setup
    : Main setup script to local build dir
  delegate_to: localhost
  template:
    src: setup.sh
    dest: "{{ local_build_dir }}"
    mode: 0700
