---
- name: >
    podman-service
    : {{ setup_name }}
    : Generate RC File
  include_tasks: generate-setup.yml
  vars:
    ansible_role: utils/alpine
    templates:
      - podman/service.rc
      - podman/service-setup.sh
    executable_files:
      - service.rc
      - service-setup.sh
