---
- include_role:
    name: service/mosquitto
  vars:
    role: mosquitto
    files:
      - setup.sh
      - mosquitto.rc
      - mosquitto.conf
    executable_files:
      - setup.sh
      - mosquitto.rc


# - include_tasks: common.yml
#   vars:
#     role: mosquitto
#     files:
#       - setup.sh
#       - mosquitto.rc
#       - mosquitto.conf
#     executable_files:
#       - setup.sh
#       - mosquitto.rc
