---
- name: >
    debian/config
    : SSHD Config File
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
  become: True
  notify: ['sshd restart']

- name: >
    debian/config
    : Ensure SSHable Group
  group:
    name: ssh
  become: True
