---
- name: >
    debian/install
    : Ensure SSHD Installed
  apt:
    name: "openssh-server"
    state: present
  become: True

- name: >
    debian/install
    : Ensure SSHD Start on Boot
  service:
    name: "ssh"
    enabled: "{{ sshd_enabled }}"
  become: True

- name: >
    debian/install
    : Create /run/sshd
  file:
    state: directory
    path: /run/sshd
  become: True
