---
- name: >
    main
    : Generate Config Files
  template:
    src: "{{ item }}"
    dest: "{{ user.home }}/.config/wofi/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  become: True
  loop:
    - config
    - style.css
