---
- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    setup_name: updates
    ansible_role: base/system
    templates:
      - alpine/setup.sh
      - alpine/update.sh
      - alpine/update-reboot.sh
    executable_files:
      - setup.sh
      - update.sh
      - update-reboot.sh
