---
- name: Clone Dmenu-Utils Repository
  git:
    repo: https://github.com/dechandler/dmenu-utils.git
    dest: "/usr/local/src/dmenu-utils"
  become: True


- name: Symlinks into Bin Directory
  file:
    path: "{{ user.home }}/bin/{{ item.dest }}"
    state: link
    src: "/usr/local/src/dmenu-utils/{{ item.src }}"
    force: True
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
  become: True
  loop:
    - src: bt-dmenu.py
      dest: bt-dmenu

    - src: ffx-dmenu.py
      dest: ffx-dmenu

    - src: nm-dmenu.sh
      dest: nm-dmenu
      
    - src: semiautokey.sh
      dest: sak

    # - src: "{{ inventory_hostname }}-xrandr-dmenu.sh"
    #   dest: xrandr-dmenu
