---
- name: >
    fedora/setup
    : Clone wofi-pass repo
  git:
    repo: https://github.com/schmidtandreas/wofi-pass.git
    dest: /usr/local/src/wofi-pass
  become: True

- name: >
    fedora/setup
    : Symlink wofi-pass to bin dir
  file:
    path: /usr/local/bin/wofi-pass
    src: /usr/local/src/wofi-pass/wofi-pass
    state: link
  become: True
