---
- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    setup_name: dnsmasq
    ansible_role: service/dnsmasq
    templates:
      - alpine/setup.sh
      - dnsmasq.conf
    executable_files:
      - setup.sh
