---
- name: >
    centos/setup
    : Ensure iptables-service package
  yum:
    name: iptables-services
  become: True

- name: >
    centos/setup
    : Stop iptables service
  systemd:
    name: iptables
    state: stopped
  become: True

- name: >
    centos/setup
    : 
  template:
    src: host.iptables
    dest: /etc/iptables/rules-save
    mode: 0600
  become: True

- name: >
    centos/setup
    : 
  systemd:
    name: iptables
    state: started
    enabled: True
  become: True
