---
user: "{{ primary_user|default('') }}"

# user:
#   name: default-user
#   groups: []
#   shell: /bin/bash
#   comment: Default User
#   ssh_private_keys: []  # references to: ssh_keys[item].key
#   authorized_keys: []  # references to: ssh_keys[item].pub
#   roles: []
#     #- desktop
#     #- shm
#     #- admin
