---
- name: >
    debian/main
    : Install
  package:
    name: dnsmasq
  become: True




- name: >
    debian/main
    : Generate config
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  become: True
