---
- name: >
    modules/batt
    : Package Dependencies
  package:
    name: "{{ name }}"
    state: present
  with_items:
    - acpi
    - brightnessctl
    - brightnessctl-udev
  become: True

- name: >
    modules/batt
    : Copy Script
  copy:
    src: modules/batt.py
    dest: /usr/local/libexec/py3status/batt.py
    mode: 0755
  become: True