---
- name: >
    modules/redshift
    : Package Dependencies
  package:
    name: redshift
    state: present
  become: True

- name: >
    modules/redshift
    : Copy Script
  copy:
    src: modules/redshift.py
    dest: /usr/local/libexec/py3status/redshift.py
    mode: 0755
  become: True