---
- name: >
    modules/vol
    : Package Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - alsa-utils
    - pavucontrol
  become: True

- name: >
    modules/vol
    : Copy Script
  copy:
    src: modules/vol.py
    dest: /usr/local/libexec/py3status/vol.py
    mode: 0755
  become: True