---
- include_role:
    name: utils/alpine
    tasks_from: generate-setup
  vars:
    setup_name: sshd
    ansible_role: service/sshd
    templates:
      - alpine/setup.sh
      - alpine/sshd_config
    executable_files:
      - setup.sh


# - name: >
#     alpine/main
#     : Login Authorized Keys
#   delegate_to: localhost
#   copy:
#     content: |
#       {% for keyname in user.authorized_keys %}
#       {{ ssh_keys[keyname].pub }}
#       {% endfor %}
#     dest: "{{ local_build_dir }}/sshd/authorized_keys"
#   vars:
#     user: "{{ login_users.0 | default(login_user) }}"
