---
- name: >
    install
    : Packages
  package:
    name: "{{ item }}"
    state: present
  become: True
  with_items:
    - py3status
    - fontawesome-fonts
    - python-pip
    - python3-pip

- name: >
    install
    : Python Packages from PyPi
  pip:
    name: i3-py
    state: present
    executable: "{{ item }}"
  with_items: [ 'pip', 'pip3' ]
  become: True

- name: >
    install
    : Ensure Script Directory
  file:
    path: /usr/local/libexec/py3status
    state: directory
    mode: 0755
  become: True

- name: >
    install
    : Install Scripts
  include_tasks: "modules/{{ module }}.yml"
  loop_control:
    loop_var: module
  with_items:
    - batt
    - redshift
    - vol
    - workspaces
    #- network
    - vpn
