---
- hosts: alpine
  gather_facts: False
  tasks:
    - include_role:
        name: utils/alpine
        tasks_from: prep-setup

- hosts: gaia,tartarus,alpine-test
  gather_facts: False
  roles:
    - base/system
    - base/login-users
    - service/sshd
    - base/extra-repos
    - base/podman

- hosts: gaia,tartarus
  gather_facts: False
  roles:
    #- base/system
    - base/mounts
    - base/network
    - base/iptables
    - service/dnsmasq
    #- service/sshd

    #- base/extra-repos
    - service/netdata
    #- base/podman
    - service/sshd-jump

- hosts: alpine-test
  gather_facts: False
  roles:
    - service/radicale
    - service/nginx

- hosts: tartarus
  gather_facts: False
  roles:
    - service/syncthing
    - service/prometheus
    - service/grafana
    - service/mosquitto
    - service/home-assistant
    - service/nginx
    - service/radicale



- hosts: alpine
  gather_facts: False
  tasks:
    - include_role:
        name: utils/alpine
        tasks_from: main-setup

    - include_role:
        name: utils/alpine
        tasks_from: apply-setup
