---
- name: iPython | Ensure Config Directory
  file:
    path: "{{ user.home }}/.ipython"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: True

- name: iPython | Copy Config
  copy:
    src: ipython_config.py
    dest: "{{ user.home }}/.ipython/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True