---
- set_fact:
    user_home: "{{ user.home | default('/home/' + user.name) }}"

- name: ZSH | Create Config Directory
  file:
    path: "{{ user_home }}/.config/oh-my-zsh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: True

- name: ZSH | Add Customizations to oh-my-zsh
  copy:
    src: custom/
    dest: "{{ user_home }}/.config/oh-my-zsh/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  become: True
  
- name: ZSH | Copy zshrc
  copy:
    src: zshrc
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  become: True